---
# tasks file for argocd

- name: add helm argo repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "https://argoproj.github.io/argo-helm"

- name: install argocd
  kubernetes.core.helm:
    name: argo-cd
    release_namespace: argocd
    chart_ref: "{{ role_path }}/files/charts/argo-cd/"
    create_namespace: true
    release_state: present
   
- name: create apps templates
  kubernetes.core.helm_template:
    chart_ref: "{{ role_path }}/files/apps/"
  register: result

- name: write templates to file
  copy:
    dest: myapps.yaml
    content: "{{ result.stdout }}"

- name: retrive myapps.yaml
  fetch:
    src: myapps.yaml
    dest: ../outputs/myapps.yaml

- name: Create apps
  kubernetes.core.k8s:
    state: present
    src: myapps.yaml
    namespace: argocd

- name: Delete from helm
  kubernetes.core.k8s:
    name: sh.helm.release.v1.argo-cd.v1
    kind: Secret
    state: absent
    namespace: argocd
    definition:
      metadata:
        labels:
          owner: helm
          name: argo-cd
